export type MajorUpdateArea =
  | 'A. Critical Fixes & Stability'
  | 'B. Certificates'
  | 'C. Scorelists & Scoring'
  | 'D. Player & Team Experience'
  | 'E. Tournaments & Seasons'
  | 'H. Public-facing Site'
  | 'M. Admin Power Tools';

export type MajorUpdateItem = { id: number; area: MajorUpdateArea; title: string };

export const MAJOR_UPDATE_CATALOG: MajorUpdateItem[] = [
  { id: 1, area: 'A. Critical Fixes & Stability', title: 'Fix Docs Portal end-to-end (uploads, previews, permissions, empty-state, mobile layout)' },
  { id: 2, area: 'A. Critical Fixes & Stability', title: 'Fix Scorelist approval realtime (no polling, event-driven refresh + optimistic UI)' },
  { id: 3, area: 'A. Critical Fixes & Stability', title: 'Fix Certificate generation overlaps (text/image/QR collision detector before save)' },
  { id: 4, area: 'A. Critical Fixes & Stability', title: 'Fix mobile responsiveness across all preview surfaces (Match Center, Scorelist, Certificates, Docs, News)' },
  { id: 5, area: 'A. Critical Fixes & Stability', title: 'Fix IST date drift in standings, audit logs, certificate dates' },
  { id: 6, area: 'A. Critical Fixes & Stability', title: 'Fix Service Worker stale cache (force update banner + skipWaiting)' },
  { id: 7, area: 'A. Critical Fixes & Stability', title: 'Fix login race conditions (admin/player/management/team) + session expiry banner' },
  { id: 8, area: 'A. Critical Fixes & Stability', title: 'Fix Apps Script timeout on large reads (pagination + ETag caching)' },
  { id: 9, area: 'A. Critical Fixes & Stability', title: 'Fix double-submit on every mutation (idempotency tokens)' },
  { id: 10, area: 'A. Critical Fixes & Stability', title: 'Fix presence flicker (online/away/offline) with smoother thresholds' },
  { id: 11, area: 'A. Critical Fixes & Stability', title: 'Fix Newsroom ticker overlap on small screens' },
  { id: 12, area: 'A. Critical Fixes & Stability', title: 'Fix Leaderboard sort stability + tie-breakers' },
  { id: 13, area: 'A. Critical Fixes & Stability', title: 'Fix Match Center undo/redo edge cases (over rollover, retired hurt)' },
  { id: 14, area: 'A. Critical Fixes & Stability', title: 'Fix scorecard import OCR mis-mapping for team abbreviations' },
  { id: 15, area: 'A. Critical Fixes & Stability', title: 'Fix broken external image fallbacks (player/team avatars)' },
  { id: 16, area: 'B. Certificates', title: '10 new premium certificate templates' },
  { id: 17, area: 'B. Certificates', title: 'Certificate approval chain: Media Manager → Secretary → Treasurer → President/VP' },
  { id: 18, area: 'B. Certificates', title: 'Approval roadmap visualization with stage badges + ETA' },
  { id: 19, area: 'B. Certificates', title: 'Bulk certificate generation (whole tournament / whole team in one click)' },
  { id: 20, area: 'B. Certificates', title: 'Certificate revocation + reissue with audit trail' },
  { id: 21, area: 'B. Certificates', title: 'QR-verifiable certificates with public verify page redesign' },
  { id: 22, area: 'B. Certificates', title: 'Player/Team dashboard pending vs approved certificate tabs' },
  { id: 23, area: 'B. Certificates', title: 'Email delivery only after final approval (with branded template)' },
  { id: 24, area: 'B. Certificates', title: 'Anti-forgery: per-certificate signed hash + watermark' },
  { id: 25, area: 'B. Certificates', title: 'Admin template designer (drag-drop fields on SVG)' },
  { id: 26, area: 'B. Certificates', title: 'Auto-fill performance stats per certificate type' },
  { id: 27, area: 'B. Certificates', title: 'Print-safe A4/Letter export with bleed marks' },
  { id: 28, area: 'B. Certificates', title: 'Multi-language certificate support (EN + regional)' },
  { id: 29, area: 'B. Certificates', title: 'Certificate analytics (issued, pending, approval lead-time)' },
  { id: 30, area: 'B. Certificates', title: 'Achievement-based auto-suggested certificates' },
  { id: 31, area: 'C. Scorelists & Scoring', title: 'Inline approve/reject for management on dashboard cards' },
  { id: 32, area: 'C. Scorelists & Scoring', title: 'Scorelist diff viewer (before vs after edit)' },
  { id: 33, area: 'C. Scorelists & Scoring', title: 'Live currently scoring indicator on home page' },
  { id: 34, area: 'C. Scorelists & Scoring', title: 'Ball-by-ball commentary auto-generated' },
  { id: 35, area: 'C. Scorelists & Scoring', title: 'Wagon wheel + pitch map per batter' },
  { id: 36, area: 'C. Scorelists & Scoring', title: 'Partnership tracker live' },
  { id: 37, area: 'C. Scorelists & Scoring', title: 'Powerplay / Death-over splits' },
  { id: 38, area: 'C. Scorelists & Scoring', title: 'Predictive score (run-rate based)' },
  { id: 39, area: 'C. Scorelists & Scoring', title: 'Scorelist PDF export with team logos' },
  { id: 40, area: 'C. Scorelists & Scoring', title: 'Scorer assignment + handoff workflow' },
  { id: 41, area: 'C. Scorelists & Scoring', title: 'Match review queue with SLA timers' },
  { id: 42, area: 'C. Scorelists & Scoring', title: 'Voice-input ball entry (mobile scorer)' },
  { id: 43, area: 'D. Player & Team Experience', title: 'Player profile redesign (hero stat card, career arc chart)' },
  { id: 44, area: 'D. Player & Team Experience', title: 'Career milestones timeline (50s, 100s, 5-wickets)' },
  { id: 45, area: 'D. Player & Team Experience', title: 'Head-to-head player comparison tool' },
  { id: 46, area: 'D. Player & Team Experience', title: 'Team profile pages with squad, history, trophies' },
  { id: 47, area: 'D. Player & Team Experience', title: 'Team dashboard for captains (availability, fitness notes)' },
  { id: 48, area: 'D. Player & Team Experience', title: 'Player availability toggle per match' },
  { id: 49, area: 'D. Player & Team Experience', title: 'Injury & fitness log (private to player + management)' },
  { id: 50, area: 'D. Player & Team Experience', title: 'Player-of-the-tournament auto-calculator' },
  { id: 51, area: 'D. Player & Team Experience', title: 'Personal best alerts + share card' },
  { id: 52, area: 'D. Player & Team Experience', title: 'Player media gallery (photos, video links)' },
  { id: 53, area: 'D. Player & Team Experience', title: 'Endorsement / sponsor field on profile' },
  { id: 54, area: 'D. Player & Team Experience', title: 'Social share cards (auto-generated PNG for milestones)' },
  { id: 55, area: 'D. Player & Team Experience', title: 'Player-to-player private DMs' },
  { id: 56, area: 'E. Tournaments & Seasons', title: 'Bracket visualizer for knockouts' },
  { id: 57, area: 'E. Tournaments & Seasons', title: 'Group-stage points table live widget' },
  { id: 58, area: 'E. Tournaments & Seasons', title: 'Tournament home page with hero, schedule, standings, top performers' },
  { id: 59, area: 'E. Tournaments & Seasons', title: 'Multi-season comparison dashboard' },
  { id: 60, area: 'E. Tournaments & Seasons', title: 'Season archive with downloadable record book PDF' },
  { id: 61, area: 'E. Tournaments & Seasons', title: 'Fixture auto-generator (round-robin, double round-robin, knockout)' },
  { id: 62, area: 'E. Tournaments & Seasons', title: 'Venue/ground management module' },
  { id: 63, area: 'E. Tournaments & Seasons', title: 'Umpire & referee roster' },
  { id: 64, area: 'E. Tournaments & Seasons', title: 'Toss recorder with auto-broadcast' },
  { id: 65, area: 'E. Tournaments & Seasons', title: 'Awards night module (nominees, voting, results)' },
  { id: 66, area: 'E. Tournaments & Seasons', title: 'Sponsorship slots per tournament (logos, mentions)' },
  { id: 87, area: 'H. Public-facing Site', title: 'New marketing landing page with hero animation' },
  { id: 90, area: 'H. Public-facing Site', title: 'Hall of Glory redesign with 3D trophy gallery' },
  { id: 92, area: 'H. Public-facing Site', title: 'Live-match public watch page (read-only ticker)' },
  { id: 93, area: 'H. Public-facing Site', title: 'About / Contact / Sponsors pages' },
  { id: 94, area: 'H. Public-facing Site', title: 'Verification page redesign (cleaner QR landing)' },
  { id: 95, area: 'H. Public-facing Site', title: 'Multi-theme toggle (light/dark/stadium)' },
  { id: 130, area: 'M. Admin Power Tools', title: 'Schema validator (Sheets vs frontend types)' },
  { id: 131, area: 'M. Admin Power Tools', title: 'Apps Script health monitor + alert' },
  { id: 133, area: 'M. Admin Power Tools', title: 'Feature flags panel (toggle modules on/off)' },
  { id: 134, area: 'M. Admin Power Tools', title: 'Maintenance mode banner + scheduled windows' },
];
