import { generateId } from '@/lib/utils';
import { ScheduleFormat, ScheduleGenerationPolicy, ScheduleMatch } from './types';

interface GeneratorInput {
  tournamentName: string;
  teams: string[];
  policy: ScheduleGenerationPolicy;
}

interface TeamAvailability {
  lastDayPlayed?: string;
  dayCounts: Record<string, number>;
}

const stageLabelByFormat: Record<ScheduleFormat, string> = {
  round_robin: 'League',
  double_round_robin: 'League',
  single_elimination: 'Knockout',
  double_elimination: 'Double Elim',
};

function toIsoDate(date: Date) {
  return date.toISOString().slice(0, 10);
}

function listDays(startDate: string, endDate: string) {
  const start = new Date(`${startDate}T00:00:00Z`);
  const end = new Date(`${endDate}T00:00:00Z`);
  const result: string[] = [];
  for (let cursor = new Date(start); cursor <= end; cursor.setUTCDate(cursor.getUTCDate() + 1)) {
    result.push(toIsoDate(cursor));
  }
  return result;
}

function combinations(teams: string[]) {
  const pairs: Array<[string, string]> = [];
  for (let i = 0; i < teams.length; i += 1) {
    for (let j = i + 1; j < teams.length; j += 1) {
      pairs.push([teams[i], teams[j]]);
    }
  }
  return pairs;
}

function matchesByFormat(format: ScheduleFormat, teams: string[]) {
  if (format === 'round_robin') return combinations(teams);
  if (format === 'double_round_robin') {
    const firstLeg = combinations(teams);
    const secondLeg = firstLeg.map(([a, b]) => [b, a] as [string, string]);
    return [...firstLeg, ...secondLeg];
  }

  if (format === 'single_elimination') {
    const seeded = [...teams];
    const out: Array<[string, string]> = [];
    while (seeded.length > 1) {
      const home = seeded.shift()!;
      const away = seeded.pop()!;
      out.push([home, away]);
    }
    return out;
  }

  const primary = combinations(teams);
  const reversed = primary.map(([a, b]) => [b, a] as [string, string]);
  return [...primary, ...reversed];
}

function canPlace(
  teamA: string,
  teamB: string,
  day: string,
  availability: Record<string, TeamAvailability>,
  allowSameDayMultipleMatches: boolean,
  allowConsecutiveDays: boolean,
) {
  const teams = [teamA, teamB];
  return teams.every((team) => {
    const state = availability[team] || { dayCounts: {} };
    const dayCount = state.dayCounts[day] || 0;
    if (!allowSameDayMultipleMatches && dayCount >= 1) return false;
    if (!allowConsecutiveDays && state.lastDayPlayed) {
      const prev = new Date(`${state.lastDayPlayed}T00:00:00Z`);
      const current = new Date(`${day}T00:00:00Z`);
      const diffDays = (current.getTime() - prev.getTime()) / (1000 * 60 * 60 * 24);
      if (diffDays === 1) return false;
    }
    return true;
  });
}

function markPlaced(teamA: string, teamB: string, day: string, availability: Record<string, TeamAvailability>) {
  [teamA, teamB].forEach((team) => {
    if (!availability[team]) availability[team] = { dayCounts: {} };
    availability[team].dayCounts[day] = (availability[team].dayCounts[day] || 0) + 1;
    availability[team].lastDayPlayed = day;
  });
}

export function generateTournamentSchedule(input: GeneratorInput): ScheduleMatch[] {
  const { teams, policy } = input;
  const days = listDays(policy.start_date, policy.end_date);
  const candidateMatches = matchesByFormat(policy.format, teams);
  const availability: Record<string, TeamAvailability> = {};

  const slots = days.flatMap((day) => {
    const dayTimes = policy.match_times.slice(0, Math.max(1, policy.matches_per_day));
    return dayTimes.map((time, slotIndex) => ({ day, time, slotIndex }));
  });

  const output: ScheduleMatch[] = [];
  const queue = [...candidateMatches];

  for (const slot of slots) {
    if (!queue.length) break;

    const nextIndex = queue.findIndex(([teamA, teamB]) => canPlace(
      teamA,
      teamB,
      slot.day,
      availability,
      policy.allow_same_day_multiple_matches,
      policy.allow_consecutive_days,
    ));

    if (nextIndex < 0) continue;

    const [teamA, teamB] = queue.splice(nextIndex, 1)[0];
    markPlaced(teamA, teamB, slot.day, availability);

    output.push({
      match_id: generateId('SCHM'),
      date: slot.day,
      time: slot.time,
      venue: policy.venues[slot.slotIndex % Math.max(1, policy.venues.length)] || 'Main Ground',
      team_a: teamA,
      team_b: teamB,
      stage: stageLabelByFormat[policy.format],
      notes: `Generated by Schedule Studio (${input.tournamentName}).`,
    });
  }

  return output;
}
