import { useState, useEffect, useMemo } from 'react';
import { useParams, Link } from 'react-router-dom';
import { Navbar } from '@/components/Navbar';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { v2api } from '@/lib/v2api';
import { verifyScorelist } from '@/lib/scorelist';
import { DigitalScorelist } from '@/lib/v2types';
import { ArrowLeft, ShieldCheck, ShieldX, Loader2 } from 'lucide-react';

const VerifyScorelist = () => {
  const { id } = useParams();
  const [scorelist, setScorelist] = useState<DigitalScorelist | null>(null);
  const [loading, setLoading] = useState(true);
  const [verifyResult, setVerifyResult] = useState<{ valid: boolean; reason?: string } | null>(null);
  const [verifying, setVerifying] = useState(false);
  const [stages, setStages] = useState<string[]>([]);

  useEffect(() => {
    (async () => {
      const all = await v2api.getScorelists();
      const found = all.find(s => s.scorelist_id === id);
      setScorelist(found || null);
      setLoading(false);
      
      if (found) {
        setVerifying(true);
        // Simulate staged verification
        setStages(['Fetching document...']);
        await new Promise(r => setTimeout(r, 500));
        setStages(prev => [...prev, 'Computing hash digest...']);
        await new Promise(r => setTimeout(r, 500));
        setStages(prev => [...prev, 'Validating signature...']);
        await new Promise(r => setTimeout(r, 500));
        const result = await verifyScorelist(found);
        setStages(prev => [...prev, 'Comparing integrity...']);
        await new Promise(r => setTimeout(r, 300));
        setVerifyResult(result);
        setStages(prev => [...prev, result.valid ? '✅ Verification complete' : '❌ Verification failed']);
        setVerifying(false);
      }
    })();
  }, [id]);

  if (loading) return (
    <div className="min-h-screen bg-background flex items-center justify-center">
      <Loader2 className="h-8 w-8 animate-spin text-primary" />
    </div>
  );

  if (!scorelist) return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <div className="container mx-auto px-4 py-20 text-center">
        <ShieldX className="h-16 w-16 text-destructive mx-auto mb-4" />
        <h1 className="font-display text-3xl mb-2">Scorelist Not Found</h1>
        <p className="text-muted-foreground mb-4">The document ID "{id}" does not exist.</p>
        <Button asChild><Link to="/"><ArrowLeft className="h-4 w-4 mr-1" /> Home</Link></Button>
      </div>
    </div>
  );

  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <div className="container mx-auto px-4 py-8 max-w-2xl space-y-6">
        <Button variant="ghost" size="sm" asChild><Link to="/"><ArrowLeft className="h-4 w-4 mr-1" /> Back</Link></Button>

        <Card className={`border-2 ${verifyResult?.valid ? 'border-primary bg-primary/5' : verifyResult ? 'border-destructive bg-destructive/5' : 'border-border'}`}>
          <CardContent className="p-8 text-center space-y-4">
            {verifying ? (
              <Loader2 className="h-12 w-12 animate-spin text-primary mx-auto" />
            ) : verifyResult?.valid ? (
              <ShieldCheck className="h-16 w-16 text-primary mx-auto" />
            ) : (
              <ShieldX className="h-16 w-16 text-destructive mx-auto" />
            )}

            <h1 className="font-display text-2xl font-bold">
              {verifying ? 'Verifying...' : verifyResult?.valid ? '✔ Authentic Scorelist' : '❌ Tampered Document'}
            </h1>

            {verifyResult && !verifyResult.valid && (
              <p className="text-destructive font-medium">{verifyResult.reason}</p>
            )}

            <div className="text-left space-y-2 mt-6">
              <div className="flex justify-between text-sm"><span className="text-muted-foreground">Document ID:</span><span className="font-mono text-xs">{scorelist.scorelist_id}</span></div>
              <div className="flex justify-between text-sm"><span className="text-muted-foreground">Scope:</span><Badge variant="outline">{scorelist.scope_type}</Badge></div>
              <div className="flex justify-between text-sm"><span className="text-muted-foreground">Generated:</span><span>{scorelist.generated_at}</span></div>
              <div className="flex justify-between text-sm"><span className="text-muted-foreground">Generated By:</span><span>{scorelist.generated_by}</span></div>
              <div className="text-sm"><span className="text-muted-foreground">Hash:</span><p className="font-mono text-xs break-all mt-1">{scorelist.hash_digest}</p></div>
            </div>

            {/* Verification Stages */}
            <div className="text-left mt-6 space-y-1">
              <p className="text-sm font-semibold mb-2">Verification Steps:</p>
              {stages.map((s, i) => (
                <div key={i} className="flex items-center gap-2 text-sm">
                  <span className={i === stages.length - 1 && !verifying ? (verifyResult?.valid ? 'text-primary' : 'text-destructive') : 'text-muted-foreground'}>
                    {i < stages.length - 1 || !verifying ? '✓' : '⏳'}
                  </span>
                  <span>{s}</span>
                </div>
              ))}
            </div>

            <p className="text-xs text-muted-foreground mt-4 italic">
              Official League Record • Tampering Invalidates Document
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default VerifyScorelist;
